### ISSUE TITLE
'wizzes' doesn't display quelled wizards

### ISSUE THREAD

**Issue by dbenoy** [YaroKasear/yaro-muf#13]
If wizards want a way to hide from the wizzes command (or go 'off duty') then it should not be quelling. Quelling should be used for safety reasons and testing, and shouldn't affect what happens when users go looking for wizards.

**Comment by YaroKasear** [comment]
I agree, and I do have a setting (Though not yet exposed.) for hiding one's self from the wizlist. I'm not sure how to detect a wizard despite quell, though. I'd hate to have to resort to manually setting wizards up on wizzes.

**Comment by dbenoy** [comment]
It can be done in FB6, but I forget how. I'll take a look when I get home. It should probably work in Proto as well.

**Comment by YaroKasear** [comment]
I think I've done it before a long time ago, but can't remember how...

**Comment by YaroKasear** [comment]
It looks like I can use "mlevel."
