### ISSUE TITLE
pub #who is broken

### ISSUE THREAD

**Issue by erisgriffon** [YaroKasear/yaro-muf#34]
Attempting to do pub #who gives the following:

--------------[ Listeners on public ]-------------
Programmer Error.  Please tell Yaro what you typed, and the following message.
lib-yaro.muf(#6), line 524; INSTR: Non-string argument (1)
System stack backtrace:
  3) lib-yaro.muf(#6) line 524, in function process_tags():
524:     s @ "^" instr if
  2) yaro-chat.muf(#7) line 192, in function who():
192:             me @ swap process_tags dup ansi_strlen 46 > if 
  1) yaro-chat.muf(#7) line 753, in function main():
753:     dup "who" paramTest if " " split swap pop who exit then
Done.

**Comment by YaroKasear** [comment]
This looks to have been fixed by the same commit that fixes #35.
