### ISSUE TITLE
using "PUB" (all caps) breaks things

### ISSUE THREAD

**Issue by erisgriffon** [YaroKasear/yaro-muf#35]
Sent command: "PUB test", got result:

Programmer Error.  Please tell Yaro what you typed, and the following message.
yaro-chat.muf(#7), line 4; INSTR: Empty string argument (2)
System stack backtrace:
  4) yaro-chat.muf(#7) line 4, in function get_channel_name():
  4:     trigger @ name swap instr dup if
  3) yaro-chat.muf(#7) line 34, in function on_channel?():
 34:     get_channel_name channel_name !
  2) yaro-chat.muf(#7) line 265, in function doSay():
265:     me @ channel_name @ on_channel? if
  1) yaro-chat.muf(#7) line 765, in function main():
764:     doSay
Done.

**Comment by YaroKasear** [comment]
Finally fixed this six years later. :P
